version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "Dependencies"
      - "Github-actions"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    labels:
      - "Dependencies"
    schedule:
      interval: "weekly"
